name: Pixeebot Fix with Semgrep

on:
    pull_request:
        types: [opened, reopened]

permissions:
    id-token: write

env:
  SONAR_ORGANIZATION: fjpgtt
  SONAR_PROJECT_KEY: fjpgtt_test-sonar-cloud-integration

jobs:
    pixeebot-fix:
        if: ${{ !startsWith(github.actor, 'pixee') }}
        name: Pixeebot Fix
        runs-on: ubuntu-latest
        timeout-minutes: 6

        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Upload file and trigger analysis
            uses: JesusCotlamee/pixee-actions/analysis-input@main
            with:
                tool: 'semgrep'
                file: README.md
