name: Upload file and trigger analysis

on:
    pull_request:
        types: [opened]
    workflow_dispatch:
        inputs:
            file:
                description: File that will be sent
                required: true
                default: 'README.md'
                type: string
            tool:
                type: choice
                description: >
                    Specific property identifying the tool or service related to the uploaded file.
                    Allowed values: 'sonar', 'codeql', 'semgrep'
                options:
                    - sonar
                    - codeql
                    - semgrep
            pr-number:
                description: PR number to trigger analysis for.
                required: false
                type: number

jobs:
    analysis-input:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        name: Upload file and trigger analysis
        timeout-minutes: 4

        steps:
            - name: Checkout repository
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - name: SonarCloud Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Upload file and trigger analysis
              uses: JesusCotlamee/pixee-actions/analysis-input@main
              with:
                  FILE: ${{ github.event.inputs.file || 'README.md' }}
                  TOOL: ${{ github.event.inputs.tool || 'sonar' }}
                  PR_NUMBER: ${{ github.event.inputs.pr-number }}
