name: Upload file and trigger analysis - dispatch

on:
    workflow_dispatch:
        inputs:
            file:
                description: File that will be sent
                required: true
                default: 'sonar-report.json'
                type: string
            tool:
                type: choice
                description: >
                    Specific property identifying the tool or service related to the uploaded file.
                    Allowed values: 'sonar', 'codeql', 'semgrep'
                options:
                    - sonar
                    - codeql
                    - semgrep
            pr-number:
                description: PR number to trigger analysis for.
                required: false
                type: number

permissions:
    contents: read
    id-token: write

jobs:
    analysis-input:
        runs-on: ubuntu-latest
        name: Upload file and trigger analysis
        timeout-minutes: 4

        steps:
            - name: Checkout repository
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - name: Upload file and trigger analysis
              uses: JesusCotlamee/pixee-actions/analysis-input@main
              with:
                  FILE: ${{ github.event.inputs.file }}
                  TOOL: ${{ github.event.inputs.tool }}
                  PR_NUMBER: ${{ github.event.inputs.pr-number }}
