name: "Submit file to code inputs"

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      url:
        description: 'Url to sent file'
        required: true
        default: 'https://d22balbl18.execute-api.us-east-1.amazonaws.com/prod/analysis-input'
        type: string
      file:
        description: 'File that will be sent'
        required: true
        default: 'README.md'
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  post-file:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: REST API with curl to pixee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL_PIXEE_UPLOAD: ${{ github.event.inputs.url || 'https://d22balbl18.execute-api.us-east-1.amazonaws.com/prod/analysis-input' }}/${{ github.repository }}/${{github.sha}}/sonar
          URL_PIXEE_TRIGGER: ${{ github.event.inputs.url || 'https://d22balbl18.execute-api.us-east-1.amazonaws.com/prod/analysis-input' }}/${{ github.repository }}/${{ github.event.number }}
          FILE_PATH: ${{ github.event.inputs.file || 'README.md' }}
        run: |
          echo "$URL_PIXEE_UPLOAD"
          echo "$URL_PIXEE_TRIGGER"
          echo "$FILE_PATH"
          
          SECRET=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://app.pixee.ai" | jq -j '.value')
          API_RESPONSE=$(curl -w "%{http_code}" -s -o /dev/null -X PUT -H "Authorization: Bearer $SECRET" -H "Content-Type: multipart/form-data" -F "file=@$FILE_PATH" $URL_PIXEE_UPLOAD)
          if [ $API_RESPONSE == 204 ]; then
          echo "File uploaded"
          if [ ${{ github.event_name }} == 'pull_request' ]; then
          echo "Call trigger"
          TRIGGER_RESPONSE=$(curl -w "%{http_code}" -s -o /dev/null -X POST -H "Authorization: Bearer $SECRET" $URL_PIXEE_TRIGGER)
          echo "Response of trigger action : $TRIGGER_RESPONSE"
          else
          echo "Manual trigger cannot trigger an analysis"
          fi
          else
          echo "File was not uploaded correctly is an unknown event"
          fi

           
